version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip install --upgrade awscli
  build:
    commands:
      - chmod +x tests.sh
      - ./tests.sh $OUTPUT_STACK_NAME
